version: '2'
services:
  app:
    container_name: hydroshare_token
    image: mdodgehawaii/hydroshare_token:latest
    environment:
      - HS_DEPLOYMENT_MODE=Dev
      - HS_CLIENT_ID=
      - HS_CLIENT_SECRET=
      - HS_CLIENT_USER=
      - HS_CLIENT_PASS=
      - IKE_TOKEN=
    command: python3 RefreshHydroShareToken.py